Repository AY2021S1-CS2113-T14-1/tp, pull requests merged in 2020-10, with the labels that each got.

#39 Added ListCommand
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/SmartHomeBot.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/CreateCommand.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/commands/RemoveCommand.java
Labels: priority.High, type.Story

#51 Save and write
  data/SmartHomeBot.txt
  src/main/java/seedu/duke/SmartHomeBot.java
  src/main/java/seedu/duke/data/framework/Appliance.java
  src/main/java/seedu/duke/data/framework/Power.java
  src/main/java/seedu/duke/storage/StorageFile.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#56 Refine Usage UI and Common Messages Class Created
  data/SmartHomeBot.txt
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/InvalidCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/commands/OffCommand.java
  src/main/java/seedu/duke/commands/OnCommand.java
  src/main/java/seedu/duke/commands/UsageCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/framework/Power.java
  src/main/java/seedu/duke/ui/TextUi.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Task

#67 Added JunitTest for Power class
  data/SmartHomeBot.txt
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/UsageCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/framework/Power.java
  src/test/java/seedu/duke/PowerUsageTest.java
  src/test/java/seedu/duke/data/SmartHomeBotTest.java
Labels: priority.Medium, type.Task

#79 Display with auto format and other minor fix
  data/SmartHomeBot.txt
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/SmartHomeBot.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/CreateCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/commands/OffCommand.java
  src/main/java/seedu/duke/commands/OnCommand.java
  src/main/java/seedu/duke/commands/UsageCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/ApplianceList.java
  src/main/java/seedu/duke/data/framework/Appliance.java
  src/main/java/seedu/duke/data/framework/Power.java
  src/main/java/seedu/duke/exceptions/InvalidPowerNumber.java
  src/main/java/seedu/duke/exceptions/PowerValueExceed.java
  src/main/java/seedu/duke/storage/StorageFile.java
  src/main/java/seedu/duke/ui/TextUi.java
  src/test/java/seedu/duke/data/SmartHomeBotTest.java
Labels: severity.Medium

#81 Adds comments for the methods and classes in data package.
  data/SmartHomeBot.txt
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/CreateCommand.java
  src/main/java/seedu/duke/commands/OnCommand.java
  src/main/java/seedu/duke/data/HomeLocations.java
  src/main/java/seedu/duke/data/framework/Appliance.java
  src/main/java/seedu/duke/data/framework/Power.java
  src/main/java/seedu/duke/storage/StorageFile.java
Labels: type.Task

#96 Completed CreateCommand, RemoveCommand, AddCommand, DeleteCommand wit…
  .gitignore
  src/main/java/seedu/smarthomebot/Parser.java
  src/main/java/seedu/smarthomebot/SmartHomeBot.java
  src/main/java/seedu/smarthomebot/commands/AddCommand.java
  src/main/java/seedu/smarthomebot/commands/CreateCommand.java
  src/main/java/seedu/smarthomebot/commands/DeleteCommand.java
  src/main/java/seedu/smarthomebot/commands/ExitCommand.java
  src/main/java/seedu/smarthomebot/commands/ListCommand.java
  src/main/java/seedu/smarthomebot/commands/OnCommand.java
  src/main/java/seedu/smarthomebot/commands/RemoveCommand.java
  src/main/java/seedu/smarthomebot/commands/UsageCommand.java
  src/main/java/seedu/smarthomebot/common/Messages.java
  src/main/java/seedu/smarthomebot/data/ApplianceList.java
  src/main/java/seedu/smarthomebot/data/LocationList.java
  src/main/java/seedu/smarthomebot/data/framework/Appliance.java
  src/main/java/seedu/smarthomebot/data/framework/Power.java
  src/main/java/seedu/smarthomebot/exceptions/ApplianceNotFoundException.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidRemovalLocationException.java
  src/main/java/seedu/smarthomebot/exceptions/LocationNotFoundException.java
  src/main/java/seedu/smarthomebot/storage/StorageFile.java
  src/main/java/seedu/smarthomebot/ui/TextUi.java
  src/test/java/seedu/smarthomebot/RemoveTest.java
  src/test/java/seedu/smarthomebot/data/LightsTest.java
  src/test/java/seedu/smarthomebot/data/SmartHomeBotTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Task

#104 Completed List Filter
  src/main/java/seedu/smarthomebot/Parser.java
  src/main/java/seedu/smarthomebot/commands/ListCommand.java
  src/main/java/seedu/smarthomebot/commands/OffCommand.java
  src/main/java/seedu/smarthomebot/commands/OnCommand.java
  src/main/java/seedu/smarthomebot/data/ApplianceList.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidFomartException.java
  src/test/java/seedu/smarthomebot/ParserTest.java
Labels: priority.Low, type.Enhancement

#103 Completed the ON/OFF Filter
  src/main/java/seedu/smarthomebot/Parser.java
  src/main/java/seedu/smarthomebot/commands/OffCommand.java
  src/main/java/seedu/smarthomebot/commands/OnCommand.java
  src/main/java/seedu/smarthomebot/data/ApplianceList.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidFomartException.java
  src/test/java/seedu/smarthomebot/ParserTest.java
Labels: priority.Low, type.Enhancement

#107 Modified the List Filter
  src/main/java/seedu/smarthomebot/Parser.java
  src/main/java/seedu/smarthomebot/commands/OffCommand.java
  src/main/java/seedu/smarthomebot/commands/OnCommand.java
  src/test/java/seedu/smarthomebot/ParserTest.java
Labels: priority.Low, type.Enhancement

#111 Parser update & bug fixes
  src/main/java/seedu/smarthomebot/Parser.java
  src/main/java/seedu/smarthomebot/commands/AddCommand.java
  src/main/java/seedu/smarthomebot/commands/CreateCommand.java
  src/main/java/seedu/smarthomebot/commands/ListCommand.java
  src/main/java/seedu/smarthomebot/commands/OffCommand.java
  src/main/java/seedu/smarthomebot/commands/OnCommand.java
  src/main/java/seedu/smarthomebot/common/Messages.java
  src/main/java/seedu/smarthomebot/data/ApplianceList.java
  src/main/java/seedu/smarthomebot/data/LocationList.java
  src/main/java/seedu/smarthomebot/exceptions/DuplicateDataException.java
  src/main/java/seedu/smarthomebot/exceptions/FileCorrupted.java
  src/main/java/seedu/smarthomebot/exceptions/FileCorruptedException.java
  src/main/java/seedu/smarthomebot/exceptions/IllegalCharacterException.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidAddCommand.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidAdditionOfAppliance.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidAddtionOfLocation.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidCommandException.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidFomartException.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidValue.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidValueException.java
  src/main/java/seedu/smarthomebot/exceptions/PowerExceedException.java
  src/main/java/seedu/smarthomebot/exceptions/PowerValueExceed.java
  src/main/java/seedu/smarthomebot/storage/StorageFile.java
  src/test/java/seedu/smarthomebot/RemoveTest.java
  src/test/java/seedu/smarthomebot/data/SmartHomeBotTest.java
Labels: severity.High, type.Task

#118 Reset command implemented
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/smarthomebot/Parser.java
  src/main/java/seedu/smarthomebot/commands/AddCommand.java
  src/main/java/seedu/smarthomebot/commands/Command.java
  src/main/java/seedu/smarthomebot/commands/CreateCommand.java
  src/main/java/seedu/smarthomebot/commands/ExitCommand.java
  src/main/java/seedu/smarthomebot/commands/HelpCommand.java
  src/main/java/seedu/smarthomebot/commands/ListCommand.java
  src/main/java/seedu/smarthomebot/commands/OffCommand.java
  src/main/java/seedu/smarthomebot/commands/OnCommand.java
  src/main/java/seedu/smarthomebot/commands/RemoveCommand.java
  src/main/java/seedu/smarthomebot/commands/ResetCommand.java
  src/main/java/seedu/smarthomebot/commands/UsageCommand.java
  src/main/java/seedu/smarthomebot/common/Messages.java
  src/main/java/seedu/smarthomebot/data/AirConditioner.java
  src/main/java/seedu/smarthomebot/data/ApplianceList.java
  src/main/java/seedu/smarthomebot/data/Fan.java
  src/main/java/seedu/smarthomebot/data/Lights.java
  src/main/java/seedu/smarthomebot/data/LocationList.java
  src/main/java/seedu/smarthomebot/data/WaterHeater.java
  src/main/java/seedu/smarthomebot/data/framework/Appliance.java
  src/main/java/seedu/smarthomebot/data/framework/Power.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidValueException.java
  src/main/java/seedu/smarthomebot/exceptions/InvalidWattageValueException.java
  src/main/java/seedu/smarthomebot/exceptions/PowerExceedException.java
  src/main/java/seedu/smarthomebot/exceptions/WattageExceedException.java
  src/main/java/seedu/smarthomebot/storage/StorageFile.java
  src/test/java/seedu/smarthomebot/DeleteTest.java
  src/test/java/seedu/smarthomebot/PowerUsageTest.java
  src/test/java/seedu/smarthomebot/data/LocationListTest.java
  src/test/java/seedu/smarthomebot/data/framework/PowerTest.java
Labels: severity.High, type.Enhancement

#119 Modified ListCommand, OnCommand and OffCommand
  src/main/java/seedu/smarthomebot/commands/Command.java
  src/main/java/seedu/smarthomebot/commands/ListCommand.java
  src/main/java/seedu/smarthomebot/commands/OffCommand.java
  src/main/java/seedu/smarthomebot/commands/OnCommand.java
Labels: priority.Medium, type.Enhancement

#134 Added Sequence Diagram in DG
  docs/DeveloperGuide.md
  docs/images/diagrams/Sequence_CommandResult.png
  docs/images/diagrams/Sequence_ExitCommand.png
  docs/images/diagrams/Sequence_HelpCommand.png
  docs/images/diagrams/Sequence_InvalidCommand.png
Labels: priority.Medium

#136 Developer guide
  docs/DeveloperGuide.md
  docs/Untitled Diagram.drawio
  docs/images/diagrams/Sequence_CreateCommand.png
  docs/images/diagrams/Sequence_MainParser.png
  docs/images/diagrams/Sequence_Parser_Add.png
  docs/images/diagrams/Sequence_Parser_Commandword.png
  docs/images/diagrams/Sequence_Parser_Create.png
  docs/images/diagrams/Sequence_Parser_Default.png
  docs/images/diagrams/Sequence_Parser_Delete.png
  docs/images/diagrams/Sequence_Parser_List.png
  docs/images/diagrams/Sequence_Parser_Off.png
  docs/images/diagrams/Sequence_Parser_On.png
  docs/images/diagrams/Sequence_Parser_Remove.png
  docs/images/diagrams/Sequence_RemoveCommand.png
  src/main/java/seedu/smarthomebot/logic/commands/CreateCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/RemoveCommand.java
Labels: priority.High

#144 Developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/diagrams/Sequence_CreateCommand.png
  docs/images/diagrams/Sequence_MainParser.png
  docs/images/diagrams/Sequence_Parser_Add.png
  docs/images/diagrams/Sequence_Parser_Commandword.png
  docs/images/diagrams/Sequence_Parser_Create.png
  docs/images/diagrams/Sequence_Parser_Default.png
  docs/images/diagrams/Sequence_Parser_Delete.png
  docs/images/diagrams/Sequence_Parser_List.png
  docs/images/diagrams/Sequence_Parser_Off.png
  docs/images/diagrams/Sequence_Parser_Remove.png
  docs/images/diagrams/Sequence_RemoveCommand.png
Labels: priority.High, type.Task
