Repository AY2021S1-CS2113-T14-1/tp, pull requests merged in 2020-11, with the labels that each got.

#182 Fixed on Bug Issue #173
  src/main/java/seedu/smarthomebot/logic/commands/ListCommand.java
Labels: priority.Medium, severity.Low, type.Bug

#186 V2.1 updates
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/zongxian-ctrl.md
  src/main/java/seedu/smarthomebot/Main.java
  src/main/java/seedu/smarthomebot/commons/Messages.java
  src/main/java/seedu/smarthomebot/logic/commands/AddCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/Command.java
  src/main/java/seedu/smarthomebot/logic/commands/CommandResult.java
  src/main/java/seedu/smarthomebot/logic/commands/CreateCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/DeleteCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/ExitCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/HelpCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/InvalidCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/ListCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/OffCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/OnCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/RemoveCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/ResetCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/UsageCommand.java
  src/main/java/seedu/smarthomebot/logic/parser/Parser.java
  src/main/java/seedu/smarthomebot/logic/parser/exceptions/EmptyParameterException.java
  src/main/java/seedu/smarthomebot/logic/parser/exceptions/IllegalCharacterException.java
  src/main/java/seedu/smarthomebot/storage/ReadStorageFile.java
  src/main/java/seedu/smarthomebot/storage/WriteStorageFile.java
  src/main/java/seedu/smarthomebot/ui/TextUi.java
Labels: type.Task

#187 V2.0 issues fix
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/_config.yml
  docs/images/diagrams/ClassDiagram_DataOverview.png
  docs/images/diagrams/ClassDiagram_UI.png
  docs/images/diagrams/Sequence_overview.png
  docs/images/favicon.ico
  docs/images/findoutmore.png
  docs/images/smarthomebot-logo.png
  docs/images/smarthomebot.jpg
  src/main/java/seedu/smarthomebot/commons/Messages.java
  src/main/java/seedu/smarthomebot/data/appliance/Appliance.java
  src/main/java/seedu/smarthomebot/data/appliance/type/AirConditioner.java
  src/main/java/seedu/smarthomebot/data/appliance/type/Fan.java
  src/main/java/seedu/smarthomebot/data/appliance/type/SmartPlug.java
  src/main/java/seedu/smarthomebot/logic/commands/Command.java
  src/main/java/seedu/smarthomebot/logic/commands/DeleteCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/ExitCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/ListCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/ResetCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/UsageCommand.java
  src/test/java/seedu/smarthomebot/data/appliance/PowerTest.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#203 V2.1 Updates
  .gitignore
  docs/UserGuide.md
  src/main/java/seedu/smarthomebot/Main.java
  src/main/java/seedu/smarthomebot/logic/commands/AddCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/Command.java
  src/main/java/seedu/smarthomebot/logic/commands/CreateCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/DeleteCommand.java
  src/main/java/seedu/smarthomebot/logic/commands/RemoveCommand.java
  src/main/java/seedu/smarthomebot/logic/parser/Parser.java
  src/main/java/seedu/smarthomebot/storage/ReadStorageFile.java
  src/main/java/seedu/smarthomebot/storage/StorageFile.java
  src/test/java/seedu/smarthomebot/logic/ParserTest.java
  src/test/java/seedu/smarthomebot/logic/commands/CommandResultTest.java
  src/test/java/seedu/smarthomebot/logic/commands/HelpCommandTest.java
  src/test/java/seedu/smarthomebot/logic/commands/InvalidCommandTest.java
Labels: type.Task

#224 V2.1 Updates
  docs/DeveloperGuide.md
  docs/images/diagrams/Sequence_Parser_Add.png
  docs/images/diagrams/Sequence_Parser_Commandword.png
  docs/images/diagrams/Sequence_Parser_Create.png
  docs/images/diagrams/Sequence_Parser_Default.png
  docs/images/diagrams/Sequence_Parser_Delete.png
  docs/images/diagrams/Sequence_Parser_List.png
  docs/images/diagrams/Sequence_Parser_Off.png
  docs/images/diagrams/Sequence_Parser_On.png
  docs/images/diagrams/Sequence_Parser_Remove.png
  src/main/java/seedu/smarthomebot/Main.java
  src/main/java/seedu/smarthomebot/logic/parser/Parser.java
Labels: type.Story

#228 Updated zongxian-ctrl.md for PPP
  docs/team/zongxian-ctrl.md
Labels: priority.High, type.Task

#239 Add TestCases for DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/smarthomebot/logic/commands/AddCommand.java
Labels: type.Task

#244 Update to UserGuide and Developer Guide
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/fanceso.md
Labels: type.Task
